// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlogWebApi.Models;

public partial class Comment
{
    public int Id { get; set; }

    public string Comment1 { get; set; }

    public DateTime CommentAt { get; set; }

    public int PostId { get; set; }

    public int UserId { get; set; }

    public bool? IsEdited { get; set; }

    public virtual Post Post { get; set; }

    public virtual ICollection<ReplyComment> ReplyComments { get; set; } = new List<ReplyComment>();

    public virtual User User { get; set; }
}