// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlogWebApi.Models;

public partial class Follower
{
    public int Id { get; set; }

    public int FollowedBy { get; set; }

    public int FollowedTo { get; set; }

    public bool? IsFollowingActive { get; set; }

    public DateTime? FollowedAt { get; set; }

    public virtual User FollowedByNavigation { get; set; }

    public virtual User FollowedToNavigation { get; set; }
}