// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlogWebApi.Models;

public partial class Post
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Desription { get; set; }

    public string Img { get; set; }

    public DateTime CreatedAt { get; set; }

    public int UserId { get; set; }

    public int CatId { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsApproved { get; set; }

    public virtual Category Cat { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<ReplyComment> ReplyComments { get; set; } = new List<ReplyComment>();

    public virtual User User { get; set; }
}