// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlogWebApi.Models;

public partial class ReplyComment
{
    public int Id { get; set; }

    public string Reply { get; set; }

    public bool? IsEdited { get; set; }

    public int CommentId { get; set; }

    public int RepliedTo { get; set; }

    public int RepliedBy { get; set; }

    public int PostId { get; set; }

    public DateTime RepliedAt { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual Post Post { get; set; }

    public virtual User RepliedByNavigation { get; set; }

    public virtual User RepliedToNavigation { get; set; }
}