// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlogWebApi.Models;

public partial class User
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string ProfilePic { get; set; }

    public int? RoleId { get; set; }

    public bool? IsActive { get; set; }

    public string Gender { get; set; }

    public int? Age { get; set; }

    public string PhoneNo { get; set; }

    public string Country { get; set; }

    public string State { get; set; }

    public string City { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? Dob { get; set; }

    public string ReasonForDeactivation { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<Post> PostApprovedByNavigations { get; set; } = new List<Post>();

    public virtual ICollection<Post> PostRejectedByNavigations { get; set; } = new List<Post>();

    public virtual ICollection<Post> PostUsers { get; set; } = new List<Post>();

    public virtual ICollection<RecentlyViewedPost> RecentlyViewedPosts { get; set; } = new List<RecentlyViewedPost>();

    public virtual ICollection<ReplyComment> ReplyCommentRepliedByNavigations { get; set; } = new List<ReplyComment>();

    public virtual ICollection<ReplyComment> ReplyCommentRepliedToNavigations { get; set; } = new List<ReplyComment>();

    public virtual Role Role { get; set; }

    public virtual ICollection<WatchLater> WatchLaters { get; set; } = new List<WatchLater>();
}